# Generated by Django 2.0.4 on 2018-06-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioForo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=45)),
                ('contrasena', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('pais', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
