# Generated by Django 2.0.4 on 2018-06-24 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_post', models.CharField(max_length=3)),
                ('titulo', models.CharField(max_length=45)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('total_likes', models.PositiveIntegerField(blank=True, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foro.UsuarioForo')),
            ],
        ),
    ]
