# Generated by Django 2.0.4 on 2018-06-24 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_noticia', models.CharField(max_length=3)),
                ('titulo', models.CharField(max_length=45)),
                ('contenido', models.TextField()),
                ('total_likes', models.PositiveIntegerField(blank=True, null=True)),
                ('total_comentarios', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropuestaSolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('contenido', models.TextField()),
                ('total_likes', models.PositiveIntegerField(blank=True, null=True)),
                ('total_comentarios', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='tema_imagen')),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='propuestasolucion',
            name='tema',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foro.Tema'),
        ),
        migrations.AddField(
            model_name='propuestasolucion',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foro.UsuarioForo'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foro.Tema'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foro.Noticia'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='propuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foro.PropuestaSolucion'),
        ),
    ]
