# Generated by Django 2.0.4 on 2018-06-26 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0004_auto_20180626_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_news', to='foro.Tema'),
        ),
    ]
