# Generated by Django 2.0.4 on 2018-06-26 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0006_auto_20180626_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioforo',
            name='key_activacion',
        ),
        migrations.RemoveField(
            model_name='usuarioforo',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='usuarioforo',
            name='validacion_email',
        ),
        migrations.AddField(
            model_name='usuarioforo',
            name='activation_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usuarioforo',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2018, 6, 26)),
        ),
    ]
