# Generated by Django 2.0.4 on 2018-06-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0007_auto_20180626_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioforo',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='usuarioforo',
            name='key_expires',
        ),
        migrations.RemoveField(
            model_name='usuarioforo',
            name='user',
        ),
        migrations.AddField(
            model_name='usuarioforo',
            name='contrasena',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='usuarioforo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usuarioforo',
            name='nombre',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='usuarioforo',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='usuarioforo',
            name='pais',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
