# Generated by Django 2.0.4 on 2018-06-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0009_auto_20180626_1104'),
        ('foro', '0005_auto_20180626_0522'),
    ]

    operations = [
    ]
