# Generated by Django 2.0.4 on 2018-06-26 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0010_merge_20180626_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.AlterField(
            model_name='propuestasolucion',
            name='tema',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_proposals', to='foro.Tema'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
