# Generated by Django 2.0.4 on 2018-06-26 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0011_auto_20180626_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuestasolucion',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_proposals', to='foro.Tema'),
        ),
    ]
